--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id text NOT NULL,
    account_id text NOT NULL,
    provider_id text NOT NULL,
    user_id text NOT NULL,
    access_token text,
    refresh_token text,
    id_token text,
    access_token_expires_at timestamp without time zone,
    refresh_token_expires_at timestamp without time zone,
    scope text,
    password text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: athletes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.athletes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    image text,
    birth_date date NOT NULL,
    age integer NOT NULL,
    birth_place text NOT NULL,
    address text NOT NULL,
    solvent integer DEFAULT 0 NOT NULL,
    category text,
    "position" text,
    user_id text NOT NULL
);


ALTER TABLE public.athletes OWNER TO postgres;

--
-- Name: athletes_health; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.athletes_health (
    id bigint NOT NULL,
    athlete_id uuid NOT NULL,
    medical_authorization boolean DEFAULT false,
    blood_type text NOT NULL,
    has_allergies text,
    takes_medications text,
    surgical_intervention text,
    injuries text,
    current_illnesses text,
    has_asthma boolean DEFAULT false
);


ALTER TABLE public.athletes_health OWNER TO postgres;

--
-- Name: athletes_health_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.athletes_health ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.athletes_health_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: athletes_representatives; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.athletes_representatives (
    id bigint NOT NULL,
    athlete_id uuid NOT NULL,
    representative_id uuid NOT NULL,
    relation text DEFAULT 'representante'::text NOT NULL,
    tutor boolean DEFAULT true NOT NULL
);


ALTER TABLE public.athletes_representatives OWNER TO postgres;

--
-- Name: athletes_representatives_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.athletes_representatives ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.athletes_representatives_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configurations; Type: TABLE; Schema: public; Owner: trkiller02
--

CREATE TABLE public.configurations (
    id text NOT NULL,
    value text NOT NULL
);


ALTER TABLE public.configurations OWNER TO trkiller02;

--
-- Name: invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    representative_id uuid NOT NULL,
    payment_date date DEFAULT now(),
    description text,
    athlete_id uuid NOT NULL,
    image_path text
);


ALTER TABLE public.invoices OWNER TO postgres;

--
-- Name: invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: trkiller02
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_id text NOT NULL,
    description text,
    type text NOT NULL,
    reference_id text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.notifications OWNER TO trkiller02;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: trkiller02
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: representatives; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.representatives (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    occupation text NOT NULL,
    height numeric(4,2),
    user_id text NOT NULL
);


ALTER TABLE public.representatives OWNER TO postgres;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    token text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    ip_address text,
    user_agent text,
    user_id text NOT NULL,
    impersonated_by text
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: two_factors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.two_factors (
    id text NOT NULL,
    secret text NOT NULL,
    backup_codes text NOT NULL,
    user_id text NOT NULL
);


ALTER TABLE public.two_factors OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    lastname text NOT NULL,
    ci_number text NOT NULL,
    phone_number text,
    email_verified boolean DEFAULT false NOT NULL,
    image text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    two_factor_enabled boolean DEFAULT false,
    role text,
    banned boolean,
    ban_reason text,
    ban_expires timestamp without time zone,
    restore_code text
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verifications (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.verifications OWNER TO postgres;

--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, account_id, provider_id, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at) FROM stdin;
s8txxV5LFl7ZYjrLzOgjm8duqEiEXWjP	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	credential	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N	\N	\N	\N	\N	\N	dfcf63e19c81c08be0d4f3961cf40ef7:e779afb1a47758a99fc6a1a01ae0a4ea11d7e2f0d71453a2d7d1ca1857bf2bc083ca89324864f45a3b60d15efc06f0ca9157aefa0024d2f584bb7f32ef5bf628	2025-04-04 03:59:32.237	2025-04-04 03:59:32.237
\.


--
-- Data for Name: athletes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.athletes (id, image, birth_date, age, birth_place, address, solvent, category, "position", user_id) FROM stdin;
\.


--
-- Data for Name: athletes_health; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.athletes_health (id, athlete_id, medical_authorization, blood_type, has_allergies, takes_medications, surgical_intervention, injuries, current_illnesses, has_asthma) FROM stdin;
\.


--
-- Data for Name: athletes_representatives; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.athletes_representatives (id, athlete_id, representative_id, relation, tutor) FROM stdin;
\.


--
-- Data for Name: configurations; Type: TABLE DATA; Schema: public; Owner: trkiller02
--

COPY public.configurations (id, value) FROM stdin;
pricing	189
\.


--
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices (id, representative_id, payment_date, description, athlete_id, image_path) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: trkiller02
--

COPY public.notifications (id, user_id, description, type, reference_id, created_at) FROM stdin;
\.


--
-- Data for Name: representatives; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.representatives (id, occupation, height, user_id) FROM stdin;
d8bfe3f7-aa3b-4d71-933a-ccde6cdfb4eb	INGENIERO	\N	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by) FROM stdin;
qUn2N5JeaRljqwM9YhrSGyeIjFQ9Bpus	2025-04-11 06:37:00.706	6g5G9hgdKqiVLv1DHzZSd9fr77vU10FP	2025-04-04 06:37:00.706	2025-04-04 06:37:00.706	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
bOdPdP4Jlv0Ob4be76Io9U94Y2W6eMyZ	2025-04-22 02:49:21.775	2IVjo8YfCBasC8cHyTUnAILjJeqpXgRs	2025-04-15 02:49:21.776	2025-04-15 02:49:21.776	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
iBKdQENkIvfiuRdzaq6R4r5BdDAt4X6Z	2025-04-26 21:42:53.55	UMPy1E2y3LQJBhCLFMMMexygCCEJmOyb	2025-04-15 04:50:23.637	2025-04-15 04:50:23.637	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
pe3ZBm1961FR0D9dK0hSTCcgSZp2sJ1g	2025-05-03 02:26:34.222	wsGhvSVr2zDVa8xGexdaObWWJJXVUBZu	2025-04-20 02:53:29.612	2025-04-20 02:53:29.612	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
XYhr0YZkRXmFZkA5Sad92caDdOQlVPc2	2025-05-05 13:35:21.685	5myxcIhAoHZBoW5ZM72snWcJnvqHl3OD	2025-04-28 13:35:21.687	2025-04-28 13:35:21.687	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
LYWBNguhsTiE2PXAw9XgBz3jYR9G545g	2025-05-05 13:36:11	Edg2hu8Cl1uYX5trIW9OhqFVxwHRZwtB	2025-04-28 13:36:11	2025-04-28 13:36:11	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
cTz8vgT8CG7Trhc9PfWMz8W6kZyInD99	2025-05-06 01:14:25.707	k1sIDDzkpeXjGnzveGt1HubZbzO2BjHM	2025-04-29 01:14:25.709	2025-04-29 01:14:25.71	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
fvcbL4ezWLDoOIgEbsblNm1OUdKxBX0B	2025-05-06 02:04:21.907	lvnESqcXUFf3K1O0blcChkvti90GRX9Y	2025-04-29 02:04:21.907	2025-04-29 02:04:21.907	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
fcq0ozgXlCpccBtFzHrupbha1qviTvtZ	2025-05-09 03:43:22.131	DW6Ao7zfHJI5RE6mXGi7xAM8hDPrb0Z1	2025-04-29 04:55:34.751	2025-04-29 04:55:34.751	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
w2l8avQAH8Z6xWmBad7LXjAA3Q2V8dPq	2025-05-09 04:47:10.449	qQP3vDjZxhllJ59BflFZhVKYijfbMSJr	2025-05-02 04:47:10.451	2025-05-02 04:47:10.451	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
eb8FmTikDRnHlUMc2FYbtLIZkKpnCKbU	2025-05-17 10:12:39.339	tYjVIBNNQRTh1hkX0zSWbuQrnTI5oyu6	2025-05-10 10:12:39.34	2025-05-10 10:12:39.34	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
DoocXnN9AqMIdEkQSAfXNAvH9DDsfJF1	2025-05-12 17:37:05.092	aG2hyVBWeD7g9Z86Dit2bXzRvOfSQKHh	2025-05-02 05:01:19.85	2025-05-02 05:01:19.85	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
SUmo69AnCfEdpexImg6Z4gUfueBKuTjv	2025-05-17 10:13:02.772	iVdYdTgSv7IVuEiZvJf3cKbAFhuQSxWz	2025-05-10 10:13:02.772	2025-05-10 10:13:02.772	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
NA3LwSOZsqbPkKebFZNydjkbfLftoyeH	2025-05-17 10:13:18.969	pwoBY0W19qlVpLm92j5MoZgvBCKHhwGQ	2025-05-10 10:13:18.969	2025-05-10 10:13:18.969	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
2VbgVvBBikzXZeqtgsdGyx8nNr5l9R5G	2025-05-16 14:16:24.323	y5hi5lk9mLWZSZG6rqnicg5Ow4moq4kt	2025-05-09 14:16:24.326	2025-05-09 14:16:24.326	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
8hP7ufYuEcRnOqrh0IMsWGORIm7kbJe9	2025-05-16 15:19:30.053	s5smRpsqSSZvd8cfzjXhhIvJYxdqn2j0	2025-05-09 15:19:30.055	2025-05-09 15:19:30.055	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
y76xvcmK7Rw3Ld9vLVRQdsVcIi0L7pdS	2025-05-16 18:55:27.985	lTyqfObB6xVSmhbFFsqaW6kUJKb4GEky	2025-05-09 18:55:27.989	2025-05-09 18:55:27.989	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
DfOqiNKsaV7CQkynOeM4FQ0d4b8cZd63	2025-05-19 05:38:26.157	7Xn9wel8dSNKA6EjcaQMzO2Pxbk3o4AG	2025-05-12 05:38:26.158	2025-05-12 05:38:26.158	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
9TF654eG8eKWh0xk6gPIYGtJtLlNM7iH	2025-05-19 13:51:43.778	BidW1RoN7XaZq9iC9gP3vXWeI98lNe5M	2025-05-12 13:51:43.778	2025-05-12 13:51:43.778	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
uKeKXbJgNaJgDAKfe2jGKpjUqzWzefjr	2025-05-19 13:52:23.856	9E11OEYjXbwVk6lLWXddo2mQsjlVLh2V	2025-05-12 13:52:23.856	2025-05-12 13:52:23.856	::1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36	NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	\N
\.


--
-- Data for Name: two_factors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.two_factors (id, secret, backup_codes, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, lastname, ci_number, phone_number, email_verified, image, created_at, updated_at, deleted_at, two_factor_enabled, role, banned, ban_reason, ban_expires, restore_code) FROM stdin;
NlXdGaXfQRVDRj2RDEtN0FCirAuyden0	OMAR AUGUSTO 	fernandez56@gmail.com	MARQUEZ FERNANDEZ	V29886348	\N	f	\N	2025-04-04 03:59:26.693	2025-04-04 03:59:26.693	\N	f	admin	\N	\N	\N	\N
\.


--
-- Data for Name: verifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verifications (id, identifier, value, expires_at, created_at, updated_at) FROM stdin;
\.


--
-- Name: athletes_health_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.athletes_health_id_seq', 15, true);


--
-- Name: athletes_representatives_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.athletes_representatives_id_seq', 16, true);


--
-- Name: invoices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoices_id_seq', 8, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: trkiller02
--

SELECT pg_catalog.setval('public.notifications_id_seq', 4, true);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: athletes_health athletes_health_athlete_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes_health
    ADD CONSTRAINT athletes_health_athlete_id_key UNIQUE (athlete_id);


--
-- Name: athletes_health athletes_health_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes_health
    ADD CONSTRAINT athletes_health_pkey PRIMARY KEY (id);


--
-- Name: athletes athletes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes
    ADD CONSTRAINT athletes_pkey PRIMARY KEY (id);


--
-- Name: athletes_representatives athletes_representatives_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes_representatives
    ADD CONSTRAINT athletes_representatives_pkey PRIMARY KEY (id);


--
-- Name: athletes athletes_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes
    ADD CONSTRAINT athletes_user_id_key UNIQUE (user_id);


--
-- Name: configurations configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: trkiller02
--

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT configurations_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: trkiller02
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: representatives representatives_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.representatives
    ADD CONSTRAINT representatives_pkey PRIMARY KEY (id);


--
-- Name: representatives representatives_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.representatives
    ADD CONSTRAINT representatives_user_id_key UNIQUE (user_id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_token_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_token_unique UNIQUE (token);


--
-- Name: two_factors two_factors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.two_factors
    ADD CONSTRAINT two_factors_pkey PRIMARY KEY (id);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: verifications verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verifications
    ADD CONSTRAINT verifications_pkey PRIMARY KEY (id);


--
-- Name: ci_number_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ci_number_pkey ON public.users USING btree (id);


--
-- Name: public_atletas_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_atletas_pkey ON public.athletes USING btree (id);


--
-- Name: public_atletas_representantes_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_atletas_representantes_pkey ON public.athletes_representatives USING btree (id);


--
-- Name: public_atletas_usuario_id_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_atletas_usuario_id_key ON public.athletes USING btree (user_id);


--
-- Name: public_facturas_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_facturas_pkey ON public.invoices USING btree (id);


--
-- Name: public_idx_fecha_pago; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_idx_fecha_pago ON public.invoices USING btree (payment_date);


--
-- Name: public_idx_solvente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX public_idx_solvente ON public.athletes USING btree (solvent);


--
-- Name: public_representantes_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_representantes_pkey ON public.representatives USING btree (id);


--
-- Name: public_representantes_usuario_id_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_representantes_usuario_id_key ON public.representatives USING btree (user_id);


--
-- Name: public_salud_atletas_pkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_salud_atletas_pkey ON public.athletes_health USING btree (id);


--
-- Name: public_unique_atleta_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX public_unique_atleta_id ON public.athletes_health USING btree (athlete_id);


--
-- Name: accounts accounts_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: athletes_representatives atletas_representantes_atleta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes_representatives
    ADD CONSTRAINT atletas_representantes_atleta_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athletes(id);


--
-- Name: athletes_representatives atletas_representantes_representante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes_representatives
    ADD CONSTRAINT atletas_representantes_representante_id_fkey FOREIGN KEY (representative_id) REFERENCES public.representatives(id);


--
-- Name: athletes atletas_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes
    ADD CONSTRAINT atletas_usuario_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: invoices facturas_atleta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT facturas_atleta_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athletes(id);


--
-- Name: invoices facturas_representante_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT facturas_representante_id_fkey FOREIGN KEY (representative_id) REFERENCES public.representatives(id);


--
-- Name: notifications notifications_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: trkiller02
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: representatives representantes_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.representatives
    ADD CONSTRAINT representantes_usuario_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: athletes_health salud_atletas_atleta_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.athletes_health
    ADD CONSTRAINT salud_atletas_atleta_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athletes(id);


--
-- Name: sessions sessions_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: two_factors two_factors_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.two_factors
    ADD CONSTRAINT two_factors_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

